from .pessoa_repository import PessoaRepository
from .coordenador_repository import CoordenadorRepository
from .estagiario_repository import EstagiarioRepository
from .matricula_repository import MatriculaRepository